global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['web:8000']  # 监控FastAPI

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']  # 监控PostgreSQL